Fixed workflow 3

diff --git a/.github/workflows/scheduled-tasks.yml b/.github/workflows/scheduled-tasks.yml
--- a/.github/workflows/scheduled-tasks.yml
+++ b/.github/workflows/scheduled-tasks.yml
@@ -17,6 +17,7 @@ jobs:
 
       - name: Check for important files
         run: |
+          touch repo_errors.txt
           test -f package.json || echo "Missing package.json" >> repo_errors.txt
           test -f public/index.html || echo "Missing index.html in public/" >> repo_errors.txt
           test -f public/data/satallite25544/index.json || echo "Missing index.json in public/" >> repo_errors.txt
@@ -24,7 +25,7 @@ jobs:
 
       - name: Validate JSON files
         run: |
-          jq . src/index.json || echo "Invalid src/index.json" >> repo_errors.txt
+          jq . public/data/satallite25544/index.json || echo "Invalid src/index.json" >> repo_errors.txt
 
       - name: Upload error log (if any)
         if: failure()
